### ISSUE TITLE
How to use this library with DropWizard 0.7.1?

### ISSUE THREAD

**Issue by applegrew** [jaredstehler/dropwizard-quartz#4]
Thanks for this library, but I having trouble making this work with 0.7. The example listed here works with 0.6. 0.7 now uses Application instead of Services. I am trying to hook in this library as below:-

	public class MyApplication extends Application<ServiceConfig> {

		@Override
		public void run(ServiceConfig conf, Environment env) throws Exception {

			ManagedScheduler quartzScheduler = new ManagedScheduler(
					StdSchedulerFactory.getDefaultScheduler(), null /*GuiceJobFactory ??*/,
					new SchedulerConfiguration(MyApplication.class
							.getPackage().getName()));
			env.lifecycle().manage(quartzScheduler);
		}

	}

Will this work? Also please note I am not sure how to get an instance of `GuiceJobFactory`.

**Comment by jaredstehler** [comment]
The ```ManagedScheduler``` is meant to be instantiated by Guice, and not manually. That's because the idea is that it's ```GuiceJobFactory``` will be pulling job instances from the guice injector, allowing you to ```@Inject``` those instances with dependencies.

If you aren't also using a dropwizard-guice implementation, you can pass in a default injector instance created via ```Guice.createInjector()```.
